name: jwst
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - pip:
    - astroquery
    - torch==2.9.0
    - numpy
    - pandas
    - matplotlib
    - scipy
    - astropy
    - tqdm
    - ipykernel
    - ipywidgets
    - reproject
